version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      # clone and build?
      - checkout 
      - run:
          name: The First Step
          command: |
            gradle test
